config/routes.rb
Rails.application.routes.draw do

  root 'plants#index'

  resources :plants

end

app/models/plant.rb
class Plant < ActiveRecord::Base

  def self.locations
    return [
      "", "wetlands", "meadow", "shady_hill",
      "entrance", "sunny hill", "lawn"
      ]
  end

  def self.sizes 
    return [
      "", "tree", "shrub", "houseplant", 
      "groundcover"
    ]
  end

  def self.months
    return [
      "", "Jan", "Feb", "Mar", "Apr",
      "May", "Jun", "July", "Aug",
      "Sept", "Oct", "Nov", "Dec"
    ]
  end

  def self.colours
    return [
      "", "Red", "Yellow", "Pink", "Green",  
      "Purple", "Orange", "Blue",  "Black", 
       "White", "Grey",  "Brown"
    ]
  end


# STALKS

  def self.shapes 
    return [ "round","square", "flat" ]
  end


# ROOTS

  def self.root_types
    return [
      "taproot", "fibrous"
    ]
  end


# LEAVES

  def self.arrangements
    return [
      "",  "opposite", "alternate", "whorled"
    ]
  end

  def self.margins
    return [ "",  "lobed", "serrated",  "entire"
    ]
  end

  def self.tip_shapes
    return [
      "",  "accute", "obtuse",  "truncated"
    ]
  end

  def self.base_shapes
    return [
      "", "acuminate", "oblique", "acute", 
      "sagittate", "rounded", "hastate",
       "cordate", "truncate"
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end
  
  protected

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
 
  def new
    @plant = Plant.new
    @locations = Plant.locations
    @sizes = Plant.sizes
    @months = Plant.months
    @colours = Plant.colours
    @arrangements = Plant.arrangements
    @margins = Plant.margins
    @tip_shapes = Plant.tip_shapes
    @base_shapes = Plant.base_shapes
    @root_types = Plant.root_types
    respond_to do |format|
      format.html
      format.json { render json: @resource }
    end
  end
 
  def create
    @resource = Plant.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, 
            status: :unprocessable_entity }
      end
    end
  end

  def index
    @collection = Plant.all
    respond_to do |format|
      format.html
      format.json { render json: @collection  }
    end
  end

  def show
    @resource = Plant.find(params['id'])
    @default_image = ""
    respond_to do |format|
      format.html
      format.json { render json: {:plant => @resource, 
                                  :locations => @resource.locations,
                                  :sizes => @resource.sizes,
                                  :colours => colours,
                                  :months => months,
                                  :arrangements => Plant.arrangements,
                                  :margins => Plant.margins,
                                  :tip_shapes => Plant.tip_shapes,
                                  :base_shapes => Plant.base_shapes,
                                  :root_types => Plant.root_types,
                                  :stalk_shapes => Plant.shapes
                                  }  
                  }
    end
  end

  def edit
    @plant = Plant.find(params['id'])
    @locations = Plant.locations
    @sizes = Plant.sizes
    @months = Plant.months
    @colours = Plant.colours
    @arrangements = Plant.arrangements
    @margins = Plant.margins
    @tip_shapes = Plant.tip_shapes
    @base_shapes = Plant.base_shapes
    @root_types = Plant.root_types
  end

  def update
    @resource = Plant.find(params['id'])
      if @resource.update(resource_params)
        redirect_to plant_url(@resource)  
      else
        format.html { render :edit }
      end
  end

  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to plant_url, 
          notice: 'successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def resource_params
    params.require(:plant).permit(:common_name, :latin_name, :image, :location, :uses, :cautions, :size,
      :fruit_colour, :fruit_has_pit, :fruit_diameter, :fruit_month, :fruit_image, :fruit_edible, :fruit_uses, :fruit_cautions,
      :flower_colour, :flower_num_petals, :flower_clustered, :flower_month, :flower_image, :flower_edible, :flower_uses, :flower_cautions,
      :leaf_arrangement, :leaf_margin, :leaf_colour, :leaf_tip_shape, :leaf_base_shape, :leaf_image, :leaf_edible, :leaf_uses, :leaf_cautions, 
      :root_runners, :root_type, :root_image, :root_edible, :root_uses, :root_cautions, 
      :stalk_shape, :stalk_climbing, :stalk_has_hairs, :stalk_colour)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flora</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="LocalFlora" ng-controller="MainCtrl">
<%= yield %>

</body>
</html>

app/views/plants/_form.html.erb
 <form novalidate class="article">
    Common Name: <input type="text" ng-model="plant.common_name" />
    Latin Name: <input type="text" ng-model="plant.latin_name" />
    
    Location: <select ng-options="location for location in locations" ng-model="plant.location"><br /></select>
    
    Size: <select ng-options="size for size in sizes" ng-model="plant.size"><br /></select><br />
    
    Uses: <input type="text" ng-model="plant.uses" />
    Cautions: <input type="text" ng-model="plant.cautions" /><br />
    Image: <input type="text" ng-model="plant.image" />

    <div>
      <h2>Flower</h2>
      Colour: <select ng-options="colour for colour in colours" ng-model="plant.flower_colour"><br /></select>
      Flowering Month: <select ng-options="month for month in months" ng-model="plant.flower_month"><br /></select>
      Number of Petals: <input type="number" ng-model="plant.flower_num_petals" />
      Clustered: <input type="checkbox" ng-model="plant.flower_clustered" />
      Edible: <input type="checkbox" ng-model="plant.flower_edible" /><br />
      Uses: <input type="text" ng-model="plant.flower_uses" />
      Cautions: <input type="text" ng-model="plant.flower_cautions" /><br />
      Image: <input type="text" ng-model="plant.flower_image" />
    </div>

    <div>
      <h2>Fruit</h2>
      Colour: <select ng-options="colour for colour in colours" ng-model="plant.fruit_colour"><br /></select>
      Fruiting Month: <select ng-options="month for month in months" ng-model="plant.fruit_month"><br /></select>
      Diameter: <input type="number" ng-model="plant.fruit_diameter" />
      Has Pit: <input type="checkbox" ng-model="plant.fruit_has_pit" />
      Edible: <input type="checkbox" ng-model="plant.fruit_edible" /><br />
      Uses: <input type="text" ng-model="plant.fruit_uses" />
      Cautions: <input type="text" ng-model="plant.fruit_cautions" /><br />
      Image: <input type="text" ng-model="plant.fruit_image" />
    </div>


    <div>
      <h2>Leaf</h2>
      Colour: <select ng-options="colour for colour in colours" ng-model="plant.leaf_colour"><br /></select>
      Arrangement: <select ng-options="arrangement for arrangement in arrangements" ng-model="plant.leaf_arrangement"><br /></select>
      Margin: <select ng-options="margin for margin in margins" ng-model="plant.leaf_margin"><br /></select><br />
      Tip Shape: <select ng-options="tip_shape for tip_shape in tip_shapes" ng-model="plant.leaf_tip_shape"><br /></select>
      Base Shape: <select ng-options="base_shape for base_shape in base_shapes" ng-model="plant.leaf_base_shape"><br /></select>
      Edible: <input type="checkbox" ng-model="plant.leaf_edible" /><br />
      Uses: <input type="text" ng-model="plant.leaf_uses" />
      Cautions: <input type="text" ng-model="plant.leaf_cautions" /><br />
      Image: <input type="text" ng-model="plant.leaf_image" />
    </div>


    <div>
      <h2>Root</h2>
      Root Type: <select ng-options="type for type in root_types" ng-model="plant.root_type"><br /></select>
      Edible: <input type="checkbox" ng-model="plant.root_edible" />
      Runners: <input type="checkbox" ng-model="plant.root_runners" /><br />
      Uses: <input type="text" ng-model="plant.root_uses" />
      Cautions: <input type="text" ng-model="plant.root_cautions" /><br />
      Image: <input type="text" ng-model="plant.root_image" />
    </div>

    <div>
      <h2>Stalk</h2>
      Colour: <select ng-options="colour for colour in colours" ng-model="plant.stalk_colour"><br /></select>
      Edible: <input type="checkbox" ng-model="plant.stalk_edible" />
      Has Hairs: <input type="checkbox" ng-model="plant.stalk_has_hairs" />
      Climbing: <input type="checkbox" ng-model="plant.stalk_climbing" /><br />
      Uses: <input type="text" ng-model="plant.stalk_uses" />
      Cautions: <input type="text" ng-model="plant.stalk_cautions" /><br />
      Image: <input type="text" ng-model="plant.stalk_image" />
    </div>
    <input type="button" ng-click="reset()" value="Reset" />
    <input type="submit" ng-click="update(plant)" value="Save" />
  </form>

app/views/plants/_rails_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="article">
    <h2>Plant</h2>
    <div class="field">
      <%= f.label :common_name %><br>
      <%= f.text_field :common_name %>
    </div>
    <div class="field">
      <%= f.label :latin_name %><br>
      <%= f.text_field :latin_name %>
    </div>
    <div class="field">
      <%= f.label :location %><br>
      <%= select(:plant, :location, @locations) %>
    </div>
    <div class="field">
      <%= f.label :size %><br>
      <%= select(:plant, :size, @sizes) %>
    </div>
    <div class="field">
      <%= f.label :uses %><br>
      <%= f.text_area :uses %>
    </div>
    <div class="field">
      <%= f.label :cautions %><br>
      <%= f.text_area :cautions %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.text_field :image %>
    </div>
  </div>

  <div class="article">
    <h2>Flower</h2>
    <div class="field">
      <%= f.label :flower_colour %><br>
      <%= select(:plant, :flower_colour, @colours) %>
    </div>
    <div class="field">
      <%= f.label :flower_month %><br>
      <%= select(:plant, :flower_month, @months) %>
    </div>
    <div class="field">
      <%= f.label :flower_num_petals %><br>
      <%= f.number_field :flower_num_petals %>
    </div>
    <div class="field">
      <%= f.label :flower_clustered %><br>
      <%= f.check_box :flower_clustered %>
    </div>
    <div class="field">
      <%= f.label :flower_edible %><br>
      <%= f.check_box :flower_edible %>
    </div>
    <div class="field">
      <%= f.label :flower_uses %><br>
      <%= f.text_area :flower_uses %>
    </div>
    <div class="field">
      <%= f.label :flower_cautions %><br>
      <%= f.text_area :flower_cautions %>
    </div>
    <div class="field">
      <%= f.label :flower_image %><br>
      <%= f.text_field :flower_image %>
    </div>
  </div>

  <div class="article">
    <h2>Fruit</h2>

  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<div class="container">

<h1>Editing Plant</h1>

<div>
  <%= render 'rails_form' %>
</div>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

</div>

app/views/plants/index.html.erb
<h1>plants index</h1>

<div ng-controller="PlantsCtrl">
  <div class="listing">
  <ul>
    <div ng-repeat="plant in plants">
      <li>
        <img src="{{plant.image}}">
        {{plant.common_name}}
        <a ng-href="/plants/{{plant.id}}">Show</a>
        <a ng-href="/plants/{{plant.id}}/edit">Edit</a>
      </li>
    </div>
  </ul>
</div>
</div>




<%= link_to "New", new_plant_url %>

app/views/plants/new.html.erb
<div class="container">

<h1>New</h1>

<%= render 'rails_form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

</div>

app/views/plants/show.html.erb
<div class="mediaCard clearfix">
  <img src="<%= @resource.image || @default_image %>">
  <div>
    <ul>
      <li><h3>Common Name: <%= @resource.common_name %><h3></li>
      <li><h4>Latin Name: <%= @resource.latin_name %></h4></li> 
      <li><h6>Location: <%= @resource.location %></h6></li> 
      <li><h6>Size: <%= @resource.size %></h6></li>
      <li>Uses: <%= @resource.uses %></li>
      <li>Cautions: <%= @resource.cautions %></li>
    </ul>
    <%= link_to 'Edit', edit_plant_path(@resource) %> | 
    <a href="/">Plants</a>
  </div>

  

  <div class="mediaCard clearfix">
    <h3>Flower</h3>
    <ul>
      <li><img src="<%= @resource.flower_image || @default_image %>"></li>
      <li>Flowering Month: <%= @resource.flower_month %></li>
      <li>Clustered: <%= @resource.flower_clustered %> </li>
      <li>Number of Petals: <%= @resource.flower_num_petals %></li>
      <li>Colour: <%= @resource.flower_colour %></li>
      <li>Uses: <%= @resource.flower_uses %></li>
      <li>Cautions: <%= @resource.flower_cautions %></li>
    </ul>
  </div>

  <div class="mediaCard clearfix">
    <h3>Fruit</h3>
    <ul>

    </ul>
  </div>

  <div class="mediaCard clearfix">
    <h3>Leaf</h3>
    <ul>

    </ul>
  </div>

  <div class="mediaCard clearfix">
    <h3>Root</h3>
    <ul>

    </ul>
  </div>

  <div class="mediaCard clearfix">
    <h3>Stalk</h3>
    <ul>

    </ul>
  </div>


</div>